# Generated by Django 3.1.4 on 2021-04-09 15:07

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20210216_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), srid=4326)),
                ('user', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
