

// Use this file to test API's 
// documentation: https://marketplace.visualstudio.com/items?itemName=humao.rest-client


GET https://www.incidentradar.com/scraper/api/incidentHitList
    ?user=admin


###


GET https://www.incidentradar.com/scraper/current_user 
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNjE4OTA2MDEwLCJlbWFpbCI6ImtvZW5AY2FydGhhLmlvIn0.xkTwnuQSItCCrrGvSvs100eP4yc4-1UEUYNjjvs_4M4
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNjE4OTA5NDAxLCJlbWFpbCI6ImtvZW5AY2FydGhhLmlvIn0.CIRYkhWPxkWlEriBWqvg2N_XaA2zLa1k3VB5CgpRg8E

