# Generated by Django 3.1.4 on 2021-01-11 08:30

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('monitorcode', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('priority_code', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_service', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=253, null=True)),
                ('longitude', models.CharField(blank=True, max_length=252, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), srid=4326)),
                ('region', models.CharField(blank=True, max_length=248, null=True)),
                ('pub_date', models.DateTimeField(blank=True, max_length=249, null=True)),
                ('incident_hash', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['comment'],
            },
        ),
    ]
