# Generated by Django 3.0.5 on 2020-09-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200930_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidents',
            old_name='geolat',
            new_name='geo_lat',
        ),
        migrations.RenameField(
            model_name='incidents',
            old_name='geolong',
            new_name='geo_long',
        ),
        migrations.AlterField(
            model_name='incidents',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
