# Generated by Django 3.1.4 on 2021-02-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20210127_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='monitorcode',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
