# Generated by Django 3.1.4 on 2021-04-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_clientlocations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientlocations',
            old_name='location',
            new_name='client_location',
        ),
    ]
