# Generated by Django 3.0.5 on 2020-10-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20201001_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='geo_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='geo_long',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
