# Generated by Django 3.0.5 on 2020-10-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20201002_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='geo_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidents',
            name='geo_long',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
