# Generated by Django 3.0.5 on 2020-10-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_auto_20201002_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='geo_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='geo_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
