# Generated by Django 3.0.5 on 2020-10-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_auto_20201002_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='geo_lat',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='geo_long',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
