# Generated by Django 3.0.5 on 2020-10-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_auto_20201002_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='geo_lat',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='geo_long',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
    ]
