# Generated by Django 3.0.5 on 2020-10-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_auto_20201002_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='geo_lat',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='geo_long',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
