# Generated by Django 3.0.5 on 2020-11-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_auto_20201002_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidents',
            options={'ordering': ['comment']},
        ),
        migrations.RenameField(
            model_name='incidents',
            old_name='title',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='incidents',
            old_name='geo_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='incidents',
            old_name='geo_long',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='description',
        ),
        migrations.AddField(
            model_name='incidents',
            name='emercency_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incidents',
            name='monitorcode',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='incidents',
            name='priority_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incidents',
            name='region',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='pubDate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
