# Generated by Django 3.0.5 on 2020-11-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0018_auto_20201106_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='monitorcode',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
