# Generated by Django 3.0.5 on 2020-11-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_auto_20201106_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='comment',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='monitorcode',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
