# Generated by Django 3.1.4 on 2021-01-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_auto_20201119_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='pubDate',
            field=models.DateTimeField(blank=True, max_length=250, null=True),
        ),
    ]
