# Generated by Django 3.0.5 on 2020-11-06 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0020_auto_20201106_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='Incidents',
            name='unique_code',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
