# Generated by Django 3.1.4 on 2021-01-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0023_auto_20210108_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='monitorcode',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
