# Generated by Django 3.1.4 on 2021-01-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0026_auto_20210108_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidents',
            old_name='pubDate',
            new_name='pub_date',
        ),
    ]
