# Generated by Django 3.1.4 on 2021-01-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0022_auto_20210108_0936'),
        ('scraper', '0027_auto_20210108_1405'),
        ('scraper', '0022_auto_20210107_1722'),
    ]

    operations = [
    ]
